import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';
import 'package:timeago/timeago.dart' as timeago;
import 'lat_lng.dart';
import 'place.dart';
import '../backend/backend.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../auth/firebase_auth/auth_util.dart';

String? getCountryFlag(String? countryName) {
  if (countryName == null) {
    return null;
  }
  final countryInfoJson = {
    "Afghanistan": {"dial_code": "+93", "code": "AF"},
    "Aland Islands": {"dial_code": "+358", "code": "AX"},
    "Albania": {"dial_code": "+355", "code": "AL"},
    "Algeria": {"dial_code": "+213", "code": "DZ"},
    "AmericanSamoa": {"dial_code": "+1684", "code": "AS"},
    "Andorra": {"dial_code": "+376", "code": "AD"},
    "Angola": {"dial_code": "+244", "code": "AO"},
    "Anguilla": {"dial_code": "+1264", "code": "AI"},
    "Antarctica": {"dial_code": "+672", "code": "AQ"},
    "Antigua and Barbuda": {"dial_code": "+1268", "code": "AG"},
    "Argentina": {"dial_code": "+54", "code": "AR"},
    "Armenia": {"dial_code": "+374", "code": "AM"},
    "Aruba": {"dial_code": "+297", "code": "AW"},
    "Australia": {"dial_code": "+61", "code": "AU"},
    "Austria": {"dial_code": "+43", "code": "AT"},
    "Azerbaijan": {"dial_code": "+994", "code": "AZ"},
    "Bahamas": {"dial_code": "+1242", "code": "BS"},
    "Bahrain": {"dial_code": "+973", "code": "BH"},
    "Bangladesh": {"dial_code": "+880", "code": "BD"},
    "Barbados": {"dial_code": "+1246", "code": "BB"},
    "Belarus": {"dial_code": "+375", "code": "BY"},
    "Belgium": {"dial_code": "+32", "code": "BE"},
    "Belize": {"dial_code": "+501", "code": "BZ"},
    "Benin": {"dial_code": "+229", "code": "BJ"},
    "Bermuda": {"dial_code": "+1441", "code": "BM"},
    "Bhutan": {"dial_code": "+975", "code": "BT"},
    "Bolivia, Plurinational State of": {"dial_code": "+591", "code": "BO"},
    "Bosnia and Herzegovina": {"dial_code": "+387", "code": "BA"},
    "Botswana": {"dial_code": "+267", "code": "BW"},
    "Brazil": {"dial_code": "+55", "code": "BR"},
    "British Indian Ocean Territory": {"dial_code": "+246", "code": "IO"},
    "Brunei Darussalam": {"dial_code": "+673", "code": "BN"},
    "Bulgaria": {"dial_code": "+359", "code": "BG"},
    "Burkina Faso": {"dial_code": "+226", "code": "BF"},
    "Burundi": {"dial_code": "+257", "code": "BI"},
    "Cambodia": {"dial_code": "+855", "code": "KH"},
    "Cameroon": {"dial_code": "+237", "code": "CM"},
    "Canada": {"dial_code": "+1", "code": "CA"},
    "Cape Verde": {"dial_code": "+238", "code": "CV"},
    "Cayman Islands": {"dial_code": "+ 345", "code": "KY"},
    "Central African Republic": {"dial_code": "+236", "code": "CF"},
    "Chad": {"dial_code": "+235", "code": "TD"},
    "Chile": {"dial_code": "+56", "code": "CL"},
    "China": {"dial_code": "+86", "code": "CN"},
    "Christmas Island": {"dial_code": "+61", "code": "CX"},
    "Cocos (Keeling) Islands": {"dial_code": "+61", "code": "CC"},
    "Colombia": {"dial_code": "+57", "code": "CO"},
    "Comoros": {"dial_code": "+269", "code": "KM"},
    "Congo": {"dial_code": "+242", "code": "CG"},
    "Congo, The Democratic Republic of the Congo": {
      "dial_code": "+243",
      "code": "CD"
    },
    "Cook Islands": {"dial_code": "+682", "code": "CK"},
    "Costa Rica": {"dial_code": "+506", "code": "CR"},
    "Cote d'Ivoire": {"dial_code": "+225", "code": "CI"},
    "Croatia": {"dial_code": "+385", "code": "HR"},
    "Cuba": {"dial_code": "+53", "code": "CU"},
    "Cyprus": {"dial_code": "+357", "code": "CY"},
    "Czech Republic": {"dial_code": "+420", "code": "CZ"},
    "Denmark": {"dial_code": "+45", "code": "DK"},
    "Djibouti": {"dial_code": "+253", "code": "DJ"},
    "Dominica": {"dial_code": "+1767", "code": "DM"},
    "Dominican Republic": {"dial_code": "+1849", "code": "DO"},
    "Ecuador": {"dial_code": "+593", "code": "EC"},
    "Egypt": {"dial_code": "+20", "code": "EG"},
    "El Salvador": {"dial_code": "+503", "code": "SV"},
    "Equatorial Guinea": {"dial_code": "+240", "code": "GQ"},
    "Eritrea": {"dial_code": "+291", "code": "ER"},
    "Estonia": {"dial_code": "+372", "code": "EE"},
    "Ethiopia": {"dial_code": "+251", "code": "ET"},
    "Falkland Islands (Malvinas)": {"dial_code": "+500", "code": "FK"},
    "Faroe Islands": {"dial_code": "+298", "code": "FO"},
    "Fiji": {"dial_code": "+679", "code": "FJ"},
    "Finland": {"dial_code": "+358", "code": "FI"},
    "France": {"dial_code": "+33", "code": "FR"},
    "French Guiana": {"dial_code": "+594", "code": "GF"},
    "French Polynesia": {"dial_code": "+689", "code": "PF"},
    "Gabon": {"dial_code": "+241", "code": "GA"},
    "Gambia": {"dial_code": "+220", "code": "GM"},
    "Georgia": {"dial_code": "+995", "code": "GE"},
    "Germany": {"dial_code": "+49", "code": "DE"},
    "Ghana": {"dial_code": "+233", "code": "GH"},
    "Gibraltar": {"dial_code": "+350", "code": "GI"},
    "Greece": {"dial_code": "+30", "code": "GR"},
    "Greenland": {"dial_code": "+299", "code": "GL"},
    "Grenada": {"dial_code": "+1473", "code": "GD"},
    "Guadeloupe": {"dial_code": "+590", "code": "GP"},
    "Guam": {"dial_code": "+1671", "code": "GU"},
    "Guatemala": {"dial_code": "+502", "code": "GT"},
    "Guernsey": {"dial_code": "+44", "code": "GG"},
    "Guinea": {"dial_code": "+224", "code": "GN"},
    "Guinea-Bissau": {"dial_code": "+245", "code": "GW"},
    "Guyana": {"dial_code": "+595", "code": "GY"},
    "Haiti": {"dial_code": "+509", "code": "HT"},
    "Holy See (Vatican City State)": {"dial_code": "+379", "code": "VA"},
    "Honduras": {"dial_code": "+504", "code": "HN"},
    "Hong Kong": {"dial_code": "+852", "code": "HK"},
    "Hungary": {"dial_code": "+36", "code": "HU"},
    "Iceland": {"dial_code": "+354", "code": "IS"},
    "India": {"dial_code": "+91", "code": "IN"},
    "Indonesia": {"dial_code": "+62", "code": "ID"},
    "Iran, Islamic Republic of Persian Gulf": {
      "dial_code": "+98",
      "code": "IR"
    },
    "Iraq": {"dial_code": "+964", "code": "IQ"},
    "Ireland": {"dial_code": "+353", "code": "IE"},
    "Isle of Man": {"dial_code": "+44", "code": "IM"},
    "Israel": {"dial_code": "+972", "code": "IL"},
    "Italy": {"dial_code": "+39", "code": "IT"},
    "Jamaica": {"dial_code": "+1876", "code": "JM"},
    "Japan": {"dial_code": "+81", "code": "JP"},
    "Jersey": {"dial_code": "+44", "code": "JE"},
    "Jordan": {"dial_code": "+962", "code": "JO"},
    "Kazakhstan": {"dial_code": "+77", "code": "KZ"},
    "Kenya": {"dial_code": "+254", "code": "KE"},
    "Kiribati": {"dial_code": "+686", "code": "KI"},
    "Korea, Democratic People's Republic of Korea": {
      "dial_code": "+850",
      "code": "KP"
    },
    "Korea, Republic of South Korea": {"dial_code": "+82", "code": "KR"},
    "Kuwait": {"dial_code": "+965", "code": "KW"},
    "Kyrgyzstan": {"dial_code": "+996", "code": "KG"},
    "Laos": {"dial_code": "+856", "code": "LA"},
    "Latvia": {"dial_code": "+371", "code": "LV"},
    "Lebanon": {"dial_code": "+961", "code": "LB"},
    "Lesotho": {"dial_code": "+266", "code": "LS"},
    "Liberia": {"dial_code": "+231", "code": "LR"},
    "Libyan Arab Jamahiriya": {"dial_code": "+218", "code": "LY"},
    "Liechtenstein": {"dial_code": "+423", "code": "LI"},
    "Lithuania": {"dial_code": "+370", "code": "LT"},
    "Luxembourg": {"dial_code": "+352", "code": "LU"},
    "Macao": {"dial_code": "+853", "code": "MO"},
    "Macedonia": {"dial_code": "+389", "code": "MK"},
    "Madagascar": {"dial_code": "+261", "code": "MG"},
    "Malawi": {"dial_code": "+265", "code": "MW"},
    "Malaysia": {"dial_code": "+60", "code": "MY"},
    "Maldives": {"dial_code": "+960", "code": "MV"},
    "Mali": {"dial_code": "+223", "code": "ML"},
    "Malta": {"dial_code": "+356", "code": "MT"},
    "Marshall Islands": {"dial_code": "+692", "code": "MH"},
    "Martinique": {"dial_code": "+596", "code": "MQ"},
    "Mauritania": {"dial_code": "+222", "code": "MR"},
    "Mauritius": {"dial_code": "+230", "code": "MU"},
    "Mayotte": {"dial_code": "+262", "code": "YT"},
    "Mexico": {"dial_code": "+52", "code": "MX"},
    "Micronesia, Federated States of Micronesia": {
      "dial_code": "+691",
      "code": "FM"
    },
    "Moldova": {"dial_code": "+373", "code": "MD"},
    "Monaco": {"dial_code": "+377", "code": "MC"},
    "Mongolia": {"dial_code": "+976", "code": "MN"},
    "Montenegro": {"dial_code": "+382", "code": "ME"},
    "Montserrat": {"dial_code": "+1664", "code": "MS"},
    "Morocco": {"dial_code": "+212", "code": "MA"},
    "Mozambique": {"dial_code": "+258", "code": "MZ"},
    "Myanmar": {"dial_code": "+95", "code": "MM"},
    "Namibia": {"dial_code": "+264", "code": "NA"},
    "Nauru": {"dial_code": "+674", "code": "NR"},
    "Nepal": {"dial_code": "+977", "code": "NP"},
    "Netherlands": {"dial_code": "+31", "code": "NL"},
    "Netherlands Antilles": {"dial_code": "+599", "code": "AN"},
    "New Caledonia": {"dial_code": "+687", "code": "NC"},
    "New Zealand": {"dial_code": "+64", "code": "NZ"},
    "Nicaragua": {"dial_code": "+505", "code": "NI"},
    "Niger": {"dial_code": "+227", "code": "NE"},
    "Nigeria": {"dial_code": "+234", "code": "NG"},
    "Niue": {"dial_code": "+683", "code": "NU"},
    "Norfolk Island": {"dial_code": "+672", "code": "NF"},
    "Northern Mariana Islands": {"dial_code": "+1670", "code": "MP"},
    "Norway": {"dial_code": "+47", "code": "NO"},
    "Oman": {"dial_code": "+968", "code": "OM"},
    "Pakistan": {"dial_code": "+92", "code": "PK"},
    "Palau": {"dial_code": "+680", "code": "PW"},
    "Palestinian Territory, Occupied": {"dial_code": "+970", "code": "PS"},
    "Panama": {"dial_code": "+507", "code": "PA"},
    "Papua New Guinea": {"dial_code": "+675", "code": "PG"},
    "Paraguay": {"dial_code": "+595", "code": "PY"},
    "Peru": {"dial_code": "+51", "code": "PE"},
    "Philippines": {"dial_code": "+63", "code": "PH"},
    "Pitcairn": {"dial_code": "+872", "code": "PN"},
    "Poland": {"dial_code": "+48", "code": "PL"},
    "Portugal": {"dial_code": "+351", "code": "PT"},
    "Puerto Rico": {"dial_code": "+1939", "code": "PR"},
    "Qatar": {"dial_code": "+974", "code": "QA"},
    "Romania": {"dial_code": "+40", "code": "RO"},
    "Russia": {"dial_code": "+7", "code": "RU"},
    "Rwanda": {"dial_code": "+250", "code": "RW"},
    "Reunion": {"dial_code": "+262", "code": "RE"},
    "Saint Barthelemy": {"dial_code": "+590", "code": "BL"},
    "Saint Helena, Ascension and Tristan Da Cunha": {
      "dial_code": "+290",
      "code": "SH"
    },
    "Saint Kitts and Nevis": {"dial_code": "+1869", "code": "KN"},
    "Saint Lucia": {"dial_code": "+1758", "code": "LC"},
    "Saint Martin": {"dial_code": "+590", "code": "MF"},
    "Saint Pierre and Miquelon": {"dial_code": "+508", "code": "PM"},
    "Saint Vincent and the Grenadines": {"dial_code": "+1784", "code": "VC"},
    "Samoa": {"dial_code": "+685", "code": "WS"},
    "San Marino": {"dial_code": "+378", "code": "SM"},
    "Sao Tome and Principe": {"dial_code": "+239", "code": "ST"},
    "Saudi Arabia": {"dial_code": "+966", "code": "SA"},
    "Senegal": {"dial_code": "+221", "code": "SN"},
    "Serbia": {"dial_code": "+381", "code": "RS"},
    "Seychelles": {"dial_code": "+248", "code": "SC"},
    "Sierra Leone": {"dial_code": "+232", "code": "SL"},
    "Singapore": {"dial_code": "+65", "code": "SG"},
    "Slovakia": {"dial_code": "+421", "code": "SK"},
    "Slovenia": {"dial_code": "+386", "code": "SI"},
    "Solomon Islands": {"dial_code": "+677", "code": "SB"},
    "Somalia": {"dial_code": "+252", "code": "SO"},
    "South Africa": {"dial_code": "+27", "code": "ZA"},
    "South Sudan": {"dial_code": "+211", "code": "SS"},
    "South Georgia and the South Sandwich Islands": {
      "dial_code": "+500",
      "code": "GS"
    },
    "Spain": {"dial_code": "+34", "code": "ES"},
    "Sri Lanka": {"dial_code": "+94", "code": "LK"},
    "Sudan": {"dial_code": "+249", "code": "SD"},
    "Suriname": {"dial_code": "+597", "code": "SR"},
    "Svalbard and Jan Mayen": {"dial_code": "+47", "code": "SJ"},
    "Swaziland": {"dial_code": "+268", "code": "SZ"},
    "Sweden": {"dial_code": "+46", "code": "SE"},
    "Switzerland": {"dial_code": "+41", "code": "CH"},
    "Syrian Arab Republic": {"dial_code": "+963", "code": "SY"},
    "Taiwan": {"dial_code": "+886", "code": "TW"},
    "Tajikistan": {"dial_code": "+992", "code": "TJ"},
    "Tanzania, United Republic of Tanzania": {
      "dial_code": "+255",
      "code": "TZ"
    },
    "Thailand": {"dial_code": "+66", "code": "TH"},
    "Timor-Leste": {"dial_code": "+670", "code": "TL"},
    "Togo": {"dial_code": "+228", "code": "TG"},
    "Tokelau": {"dial_code": "+690", "code": "TK"},
    "Tonga": {"dial_code": "+676", "code": "TO"},
    "Trinidad and Tobago": {"dial_code": "+1868", "code": "TT"},
    "Tunisia": {"dial_code": "+216", "code": "TN"},
    "Turkey": {"dial_code": "+90", "code": "TR"},
    "Turkmenistan": {"dial_code": "+993", "code": "TM"},
    "Turks and Caicos Islands": {"dial_code": "+1649", "code": "TC"},
    "Tuvalu": {"dial_code": "+688", "code": "TV"},
    "Uganda": {"dial_code": "+256", "code": "UG"},
    "Ukraine": {"dial_code": "+380", "code": "UA"},
    "United Arab Emirates": {"dial_code": "+971", "code": "AE"},
    "United Kingdom": {"dial_code": "+44", "code": "GB"},
    "United States": {"dial_code": "+1", "code": "US"},
    "Uruguay": {"dial_code": "+598", "code": "UY"},
    "Uzbekistan": {"dial_code": "+998", "code": "UZ"},
    "Vanuatu": {"dial_code": "+678", "code": "VU"},
    "Venezuela, Bolivarian Republic of Venezuela": {
      "dial_code": "+58",
      "code": "VE"
    },
    "Vietnam": {"dial_code": "+84", "code": "VN"},
    "Virgin Islands, British": {"dial_code": "+1284", "code": "VG"},
    "Virgin Islands, U.S.": {"dial_code": "+1340", "code": "VI"},
    "Wallis and Futuna": {"dial_code": "+681", "code": "WF"},
    "Yemen": {"dial_code": "+967", "code": "YE"},
    "Zambia": {"dial_code": "+260", "code": "ZM"},
    "Zimbabwe": {"dial_code": "+263", "code": "ZW"}
  };

  final countryCode = countryInfoJson[countryName]?["code"];

  if (countryCode != null) {
    final countryCodeInLowerCase = countryCode.toLowerCase();
    return 'https://flagcdn.com/h80/$countryCodeInLowerCase.png';
  }

  return null;
}

List<String> getCountryList() {
  final countries = ["Colombia"];

  return countries;
}

String? getDialCode(String? countryName) {
  if (countryName == null) {
    return null;
  }
  final countryInfoJson = {
    "Afghanistan": {"dial_code": "+93", "code": "AF"},
    "Aland Islands": {"dial_code": "+358", "code": "AX"},
    "Albania": {"dial_code": "+355", "code": "AL"},
    "Algeria": {"dial_code": "+213", "code": "DZ"},
    "AmericanSamoa": {"dial_code": "+1684", "code": "AS"},
    "Andorra": {"dial_code": "+376", "code": "AD"},
    "Angola": {"dial_code": "+244", "code": "AO"},
    "Anguilla": {"dial_code": "+1264", "code": "AI"},
    "Antarctica": {"dial_code": "+672", "code": "AQ"},
    "Antigua and Barbuda": {"dial_code": "+1268", "code": "AG"},
    "Argentina": {"dial_code": "+54", "code": "AR"},
    "Armenia": {"dial_code": "+374", "code": "AM"},
    "Aruba": {"dial_code": "+297", "code": "AW"},
    "Australia": {"dial_code": "+61", "code": "AU"},
    "Austria": {"dial_code": "+43", "code": "AT"},
    "Azerbaijan": {"dial_code": "+994", "code": "AZ"},
    "Bahamas": {"dial_code": "+1242", "code": "BS"},
    "Bahrain": {"dial_code": "+973", "code": "BH"},
    "Bangladesh": {"dial_code": "+880", "code": "BD"},
    "Barbados": {"dial_code": "+1246", "code": "BB"},
    "Belarus": {"dial_code": "+375", "code": "BY"},
    "Belgium": {"dial_code": "+32", "code": "BE"},
    "Belize": {"dial_code": "+501", "code": "BZ"},
    "Benin": {"dial_code": "+229", "code": "BJ"},
    "Bermuda": {"dial_code": "+1441", "code": "BM"},
    "Bhutan": {"dial_code": "+975", "code": "BT"},
    "Bolivia, Plurinational State of": {"dial_code": "+591", "code": "BO"},
    "Bosnia and Herzegovina": {"dial_code": "+387", "code": "BA"},
    "Botswana": {"dial_code": "+267", "code": "BW"},
    "Brazil": {"dial_code": "+55", "code": "BR"},
    "British Indian Ocean Territory": {"dial_code": "+246", "code": "IO"},
    "Brunei Darussalam": {"dial_code": "+673", "code": "BN"},
    "Bulgaria": {"dial_code": "+359", "code": "BG"},
    "Burkina Faso": {"dial_code": "+226", "code": "BF"},
    "Burundi": {"dial_code": "+257", "code": "BI"},
    "Cambodia": {"dial_code": "+855", "code": "KH"},
    "Cameroon": {"dial_code": "+237", "code": "CM"},
    "Canada": {"dial_code": "+1", "code": "CA"},
    "Cape Verde": {"dial_code": "+238", "code": "CV"},
    "Cayman Islands": {"dial_code": "+ 345", "code": "KY"},
    "Central African Republic": {"dial_code": "+236", "code": "CF"},
    "Chad": {"dial_code": "+235", "code": "TD"},
    "Chile": {"dial_code": "+56", "code": "CL"},
    "China": {"dial_code": "+86", "code": "CN"},
    "Christmas Island": {"dial_code": "+61", "code": "CX"},
    "Cocos (Keeling) Islands": {"dial_code": "+61", "code": "CC"},
    "Colombia": {"dial_code": "+57", "code": "CO"},
    "Comoros": {"dial_code": "+269", "code": "KM"},
    "Congo": {"dial_code": "+242", "code": "CG"},
    "Congo, The Democratic Republic of the Congo": {
      "dial_code": "+243",
      "code": "CD"
    },
    "Cook Islands": {"dial_code": "+682", "code": "CK"},
    "Costa Rica": {"dial_code": "+506", "code": "CR"},
    "Cote d'Ivoire": {"dial_code": "+225", "code": "CI"},
    "Croatia": {"dial_code": "+385", "code": "HR"},
    "Cuba": {"dial_code": "+53", "code": "CU"},
    "Cyprus": {"dial_code": "+357", "code": "CY"},
    "Czech Republic": {"dial_code": "+420", "code": "CZ"},
    "Denmark": {"dial_code": "+45", "code": "DK"},
    "Djibouti": {"dial_code": "+253", "code": "DJ"},
    "Dominica": {"dial_code": "+1767", "code": "DM"},
    "Dominican Republic": {"dial_code": "+1849", "code": "DO"},
    "Ecuador": {"dial_code": "+593", "code": "EC"},
    "Egypt": {"dial_code": "+20", "code": "EG"},
    "El Salvador": {"dial_code": "+503", "code": "SV"},
    "Equatorial Guinea": {"dial_code": "+240", "code": "GQ"},
    "Eritrea": {"dial_code": "+291", "code": "ER"},
    "Estonia": {"dial_code": "+372", "code": "EE"},
    "Ethiopia": {"dial_code": "+251", "code": "ET"},
    "Falkland Islands (Malvinas)": {"dial_code": "+500", "code": "FK"},
    "Faroe Islands": {"dial_code": "+298", "code": "FO"},
    "Fiji": {"dial_code": "+679", "code": "FJ"},
    "Finland": {"dial_code": "+358", "code": "FI"},
    "France": {"dial_code": "+33", "code": "FR"},
    "French Guiana": {"dial_code": "+594", "code": "GF"},
    "French Polynesia": {"dial_code": "+689", "code": "PF"},
    "Gabon": {"dial_code": "+241", "code": "GA"},
    "Gambia": {"dial_code": "+220", "code": "GM"},
    "Georgia": {"dial_code": "+995", "code": "GE"},
    "Germany": {"dial_code": "+49", "code": "DE"},
    "Ghana": {"dial_code": "+233", "code": "GH"},
    "Gibraltar": {"dial_code": "+350", "code": "GI"},
    "Greece": {"dial_code": "+30", "code": "GR"},
    "Greenland": {"dial_code": "+299", "code": "GL"},
    "Grenada": {"dial_code": "+1473", "code": "GD"},
    "Guadeloupe": {"dial_code": "+590", "code": "GP"},
    "Guam": {"dial_code": "+1671", "code": "GU"},
    "Guatemala": {"dial_code": "+502", "code": "GT"},
    "Guernsey": {"dial_code": "+44", "code": "GG"},
    "Guinea": {"dial_code": "+224", "code": "GN"},
    "Guinea-Bissau": {"dial_code": "+245", "code": "GW"},
    "Guyana": {"dial_code": "+595", "code": "GY"},
    "Haiti": {"dial_code": "+509", "code": "HT"},
    "Holy See (Vatican City State)": {"dial_code": "+379", "code": "VA"},
    "Honduras": {"dial_code": "+504", "code": "HN"},
    "Hong Kong": {"dial_code": "+852", "code": "HK"},
    "Hungary": {"dial_code": "+36", "code": "HU"},
    "Iceland": {"dial_code": "+354", "code": "IS"},
    "India": {"dial_code": "+91", "code": "IN"},
    "Indonesia": {"dial_code": "+62", "code": "ID"},
    "Iran, Islamic Republic of Persian Gulf": {
      "dial_code": "+98",
      "code": "IR"
    },
    "Iraq": {"dial_code": "+964", "code": "IQ"},
    "Ireland": {"dial_code": "+353", "code": "IE"},
    "Isle of Man": {"dial_code": "+44", "code": "IM"},
    "Israel": {"dial_code": "+972", "code": "IL"},
    "Italy": {"dial_code": "+39", "code": "IT"},
    "Jamaica": {"dial_code": "+1876", "code": "JM"},
    "Japan": {"dial_code": "+81", "code": "JP"},
    "Jersey": {"dial_code": "+44", "code": "JE"},
    "Jordan": {"dial_code": "+962", "code": "JO"},
    "Kazakhstan": {"dial_code": "+77", "code": "KZ"},
    "Kenya": {"dial_code": "+254", "code": "KE"},
    "Kiribati": {"dial_code": "+686", "code": "KI"},
    "Korea, Democratic People's Republic of Korea": {
      "dial_code": "+850",
      "code": "KP"
    },
    "Korea, Republic of South Korea": {"dial_code": "+82", "code": "KR"},
    "Kuwait": {"dial_code": "+965", "code": "KW"},
    "Kyrgyzstan": {"dial_code": "+996", "code": "KG"},
    "Laos": {"dial_code": "+856", "code": "LA"},
    "Latvia": {"dial_code": "+371", "code": "LV"},
    "Lebanon": {"dial_code": "+961", "code": "LB"},
    "Lesotho": {"dial_code": "+266", "code": "LS"},
    "Liberia": {"dial_code": "+231", "code": "LR"},
    "Libyan Arab Jamahiriya": {"dial_code": "+218", "code": "LY"},
    "Liechtenstein": {"dial_code": "+423", "code": "LI"},
    "Lithuania": {"dial_code": "+370", "code": "LT"},
    "Luxembourg": {"dial_code": "+352", "code": "LU"},
    "Macao": {"dial_code": "+853", "code": "MO"},
    "Macedonia": {"dial_code": "+389", "code": "MK"},
    "Madagascar": {"dial_code": "+261", "code": "MG"},
    "Malawi": {"dial_code": "+265", "code": "MW"},
    "Malaysia": {"dial_code": "+60", "code": "MY"},
    "Maldives": {"dial_code": "+960", "code": "MV"},
    "Mali": {"dial_code": "+223", "code": "ML"},
    "Malta": {"dial_code": "+356", "code": "MT"},
    "Marshall Islands": {"dial_code": "+692", "code": "MH"},
    "Martinique": {"dial_code": "+596", "code": "MQ"},
    "Mauritania": {"dial_code": "+222", "code": "MR"},
    "Mauritius": {"dial_code": "+230", "code": "MU"},
    "Mayotte": {"dial_code": "+262", "code": "YT"},
    "Mexico": {"dial_code": "+52", "code": "MX"},
    "Micronesia, Federated States of Micronesia": {
      "dial_code": "+691",
      "code": "FM"
    },
    "Moldova": {"dial_code": "+373", "code": "MD"},
    "Monaco": {"dial_code": "+377", "code": "MC"},
    "Mongolia": {"dial_code": "+976", "code": "MN"},
    "Montenegro": {"dial_code": "+382", "code": "ME"},
    "Montserrat": {"dial_code": "+1664", "code": "MS"},
    "Morocco": {"dial_code": "+212", "code": "MA"},
    "Mozambique": {"dial_code": "+258", "code": "MZ"},
    "Myanmar": {"dial_code": "+95", "code": "MM"},
    "Namibia": {"dial_code": "+264", "code": "NA"},
    "Nauru": {"dial_code": "+674", "code": "NR"},
    "Nepal": {"dial_code": "+977", "code": "NP"},
    "Netherlands": {"dial_code": "+31", "code": "NL"},
    "Netherlands Antilles": {"dial_code": "+599", "code": "AN"},
    "New Caledonia": {"dial_code": "+687", "code": "NC"},
    "New Zealand": {"dial_code": "+64", "code": "NZ"},
    "Nicaragua": {"dial_code": "+505", "code": "NI"},
    "Niger": {"dial_code": "+227", "code": "NE"},
    "Nigeria": {"dial_code": "+234", "code": "NG"},
    "Niue": {"dial_code": "+683", "code": "NU"},
    "Norfolk Island": {"dial_code": "+672", "code": "NF"},
    "Northern Mariana Islands": {"dial_code": "+1670", "code": "MP"},
    "Norway": {"dial_code": "+47", "code": "NO"},
    "Oman": {"dial_code": "+968", "code": "OM"},
    "Pakistan": {"dial_code": "+92", "code": "PK"},
    "Palau": {"dial_code": "+680", "code": "PW"},
    "Palestinian Territory, Occupied": {"dial_code": "+970", "code": "PS"},
    "Panama": {"dial_code": "+507", "code": "PA"},
    "Papua New Guinea": {"dial_code": "+675", "code": "PG"},
    "Paraguay": {"dial_code": "+595", "code": "PY"},
    "Peru": {"dial_code": "+51", "code": "PE"},
    "Philippines": {"dial_code": "+63", "code": "PH"},
    "Pitcairn": {"dial_code": "+872", "code": "PN"},
    "Poland": {"dial_code": "+48", "code": "PL"},
    "Portugal": {"dial_code": "+351", "code": "PT"},
    "Puerto Rico": {"dial_code": "+1939", "code": "PR"},
    "Qatar": {"dial_code": "+974", "code": "QA"},
    "Romania": {"dial_code": "+40", "code": "RO"},
    "Russia": {"dial_code": "+7", "code": "RU"},
    "Rwanda": {"dial_code": "+250", "code": "RW"},
    "Reunion": {"dial_code": "+262", "code": "RE"},
    "Saint Barthelemy": {"dial_code": "+590", "code": "BL"},
    "Saint Helena, Ascension and Tristan Da Cunha": {
      "dial_code": "+290",
      "code": "SH"
    },
    "Saint Kitts and Nevis": {"dial_code": "+1869", "code": "KN"},
    "Saint Lucia": {"dial_code": "+1758", "code": "LC"},
    "Saint Martin": {"dial_code": "+590", "code": "MF"},
    "Saint Pierre and Miquelon": {"dial_code": "+508", "code": "PM"},
    "Saint Vincent and the Grenadines": {"dial_code": "+1784", "code": "VC"},
    "Samoa": {"dial_code": "+685", "code": "WS"},
    "San Marino": {"dial_code": "+378", "code": "SM"},
    "Sao Tome and Principe": {"dial_code": "+239", "code": "ST"},
    "Saudi Arabia": {"dial_code": "+966", "code": "SA"},
    "Senegal": {"dial_code": "+221", "code": "SN"},
    "Serbia": {"dial_code": "+381", "code": "RS"},
    "Seychelles": {"dial_code": "+248", "code": "SC"},
    "Sierra Leone": {"dial_code": "+232", "code": "SL"},
    "Singapore": {"dial_code": "+65", "code": "SG"},
    "Slovakia": {"dial_code": "+421", "code": "SK"},
    "Slovenia": {"dial_code": "+386", "code": "SI"},
    "Solomon Islands": {"dial_code": "+677", "code": "SB"},
    "Somalia": {"dial_code": "+252", "code": "SO"},
    "South Africa": {"dial_code": "+27", "code": "ZA"},
    "South Sudan": {"dial_code": "+211", "code": "SS"},
    "South Georgia and the South Sandwich Islands": {
      "dial_code": "+500",
      "code": "GS"
    },
    "Spain": {"dial_code": "+34", "code": "ES"},
    "Sri Lanka": {"dial_code": "+94", "code": "LK"},
    "Sudan": {"dial_code": "+249", "code": "SD"},
    "Suriname": {"dial_code": "+597", "code": "SR"},
    "Svalbard and Jan Mayen": {"dial_code": "+47", "code": "SJ"},
    "Swaziland": {"dial_code": "+268", "code": "SZ"},
    "Sweden": {"dial_code": "+46", "code": "SE"},
    "Switzerland": {"dial_code": "+41", "code": "CH"},
    "Syrian Arab Republic": {"dial_code": "+963", "code": "SY"},
    "Taiwan": {"dial_code": "+886", "code": "TW"},
    "Tajikistan": {"dial_code": "+992", "code": "TJ"},
    "Tanzania, United Republic of Tanzania": {
      "dial_code": "+255",
      "code": "TZ"
    },
    "Thailand": {"dial_code": "+66", "code": "TH"},
    "Timor-Leste": {"dial_code": "+670", "code": "TL"},
    "Togo": {"dial_code": "+228", "code": "TG"},
    "Tokelau": {"dial_code": "+690", "code": "TK"},
    "Tonga": {"dial_code": "+676", "code": "TO"},
    "Trinidad and Tobago": {"dial_code": "+1868", "code": "TT"},
    "Tunisia": {"dial_code": "+216", "code": "TN"},
    "Turkey": {"dial_code": "+90", "code": "TR"},
    "Turkmenistan": {"dial_code": "+993", "code": "TM"},
    "Turks and Caicos Islands": {"dial_code": "+1649", "code": "TC"},
    "Tuvalu": {"dial_code": "+688", "code": "TV"},
    "Uganda": {"dial_code": "+256", "code": "UG"},
    "Ukraine": {"dial_code": "+380", "code": "UA"},
    "United Arab Emirates": {"dial_code": "+971", "code": "AE"},
    "United Kingdom": {"dial_code": "+44", "code": "GB"},
    "United States": {"dial_code": "+1", "code": "US"},
    "Uruguay": {"dial_code": "+598", "code": "UY"},
    "Uzbekistan": {"dial_code": "+998", "code": "UZ"},
    "Vanuatu": {"dial_code": "+678", "code": "VU"},
    "Venezuela, Bolivarian Republic of Venezuela": {
      "dial_code": "+58",
      "code": "VE"
    },
    "Vietnam": {"dial_code": "+84", "code": "VN"},
    "Virgin Islands, British": {"dial_code": "+1284", "code": "VG"},
    "Virgin Islands, U.S.": {"dial_code": "+1340", "code": "VI"},
    "Wallis and Futuna": {"dial_code": "+681", "code": "WF"},
    "Yemen": {"dial_code": "+967", "code": "YE"},
    "Zambia": {"dial_code": "+260", "code": "ZM"},
    "Zimbabwe": {"dial_code": "+263", "code": "ZW"}
  };

  final countryDialCode = countryInfoJson[countryName]?["dial_code"];

  if (countryDialCode != null) {
    return countryDialCode;
  }

  return null;
}

List<String> getLocationList(String? ciudadElegida) {
  if (ciudadElegida == 'Bogota') {
    return [
      'Antonio Nariño',
      'Barrios Unidos',
      'Bosa',
      'Chapinero',
      'Ciudad Bolívar',
      'Engativá',
      'Fontibón',
      'Kennedy',
      'La Candelaria',
      'Los Mártires',
      'Puente Aranda',
      'Rafael Uribe Uribe',
      'San Cristobal',
      'Santa Fe',
      'Suba',
      'Sumapaz',
      'Teusaquillo',
      'Tunjuelito',
      'Usaquén',
      'Usme'
    ];
  } else if (ciudadElegida == 'Villavicencio') {
    return ['Orange', 'Gray', 'Red'];
  } else if (ciudadElegida == 'Mexico') {
    return ['Hola', 'Como', 'Chao'];
  }
  return ['vacio'];
}

List<String> getCitiesList() {
  return ['Bogota'];
}

List<String> getNeighborhoodsList(String? localidadElegida) {
  if (localidadElegida == 'Antonio Nariño') {
    return [
      'Caracas',
      'Cinco de Noviembre',
      'Ciudad Berna',
      'Ciudad Jardín',
      'Eduardo Freí',
      'La Fragua',
      'La Fraguita',
      'La Hortúa',
      'Luna Park',
      'Policarpa',
      'Restrepo',
      'Restrepo Occidental',
      'San Antonio',
      'San Jorge Central II Sector',
      'Santander',
      'Santander Sur',
      'Sena',
      'Sevilla',
      'Villa Mayor Oriental'
    ];
  } else if (localidadElegida == 'Barrios Unidos') {
    return [
      '1 de Noviembre',
      '12 de Ocutbre',
      'Alcázares Norte',
      'Baquero',
      'Benjamín Herrera',
      'Chapinero Noroccidental',
      'Colombia',
      'Concepción Norte',
      'Conjunto Residencial Calle 100',
      'Doce de Octubre',
      'El Labrador',
      'El Rosario',
      'Entre Ríos',
      'Escuela Militar',
      'Jorge Eliécer Gaitán',
      'José Joaquín Vargas',
      'Juan XXIII Norte',
      'La Aurora',
      'La Castellana',
      'La Esperanza',
      'La Libertad',
      'La Merced Norte',
      'La Patria',
      'La Paz',
      'Los Alcázares',
      'Los Andes',
      'Metrópolis',
      'Modelo Norte',
      'Muequetá',
      'Polo Club',
      'Popular Modelo',
      'Quinta Mutis',
      'Rafael Uribe',
      'Rincón Del Salitre',
      'Rionegro',
      'San Felipe',
      'San Fernando',
      'San Fernando Occidental',
      'San Miguel',
      'Santa Sofía',
      'Siete de Agosto',
      'Simón Bolívar',
      'Urbanización San Martín',
      'Villa Calasanz',
      'Vizcaya'
    ];
  } else if (localidadElegida == 'Bosa') {
    return [
      'Amaru',
      'Andalucía I',
      'Andalucía II',
      'Antonia Santos',
      'Antonio Nariño',
      'Argelia',
      'Berlín',
      'Berlín de Bosa La Libertad III',
      'Betania',
      'Betania',
      'Bosa',
      'Bosa Nova',
      'Bosa Nova II Sector',
      'Bosa Palestina',
      'Bosalinda (Holdebrando Olarte)',
      'Bosques de Meryland',
      'Brasil',
      'Brasil II Sector',
      'Brasil II Segunda Etapa',
      'Brasil Lopez y Piñeros',
      'Brasil Materas Acacias S.Jorge',
      'Brasil Sector Barreto',
      'Brasil Sector Portal y Castillo',
      'Brasilia ',
      'Brasilia-La Estación',
      'Caldas',
      'Campo Hermoso',
      'Campo Hermoso',
      'Campo Verde',
      'Cañaveralejo',
      'Carlos Albán',
      'Casa Nueva',
      'Charles de Gaulle',
      'Chicala',
      'Ciudadela el Recreo',
      'Ciudadela La Libertad',
      'Claretiano',
      'El Anhelo',
      'El Bosque de Bosa',
      'El Cauce',
      'El Corzo',
      'El Diamante',
      'El Jardín',
      'El Libertador',
      'El Llano',
      'El Matorral',
      'El Matorral de San Bernardino',
      'El Motorista',
      'El Palmar',
      'El Paradero',
      'El Portal de Bosa',
      'El Portal de La Libertad',
      'El Porvenir',
      'El Progreso',
      'El Recuerdo',
      'El Recuerdo de Santa Fe',
      'El Regalo',
      'El Retazo',
      'El Rincón de Bosa',
      'El Rodeo',
      'El Sauce',
      'El Toche',
      'El Triunfo',
      'El Triunfo de San Bernardino',
      'Escocia',
      'Finca La Esperanza',
      'Getsemaní',
      'Grancolombiano I',
      'Grancolombiano II',
      'Gualoche',
      'Hermanos Barragán',
      'Holanda',
      'Hortelanos de Escocia',
      'Humberto Valencia',
      'Industrial',
      'Islandia',
      'Israelita',
      'Jardines del Apogeo',
      'Jiménez de Quesada',
      'Jorge Uribe Botero',
      'José Antonio Galán',
      'José María Carbonel',
      'La Amistad',
      'La Arboleda',
      'La Azucena',
      'La Cabaña',
      'La Concepción',
      'La Dulcinea',
      'La Esmeralda',
      'La Esperanza',
      'La Estación',
      'La Estanzuela I',
      'La Estanzuela II',
      'La Florida',
      'La Fontana de Bosa-La Libertad',
      'La Granjita',
      'La Ilusión',
      'La Independencia',
      'La Libertad I',
      'La Libertad II',
      'La Libertad III',
      'La Libertad IV',
      'La Magnolia',
      'La María',
      'La Palma',
      'La Paz',
      'La Portada',
      'La Portadita',
      'La Riviera',
      'La Suerte',
      'La Unión',
      'La Vega de San Bernardino Bajo',
      'La Veguita',
      'Las Margaritas',
      'Las Vegas',
      'Laureles',
      'Llano Oriental',
      'Llanos de Bosa',
      'Los Centauros',
      'Los Ocales',
      'Los Sauces',
      'Manzanares',
      'Miami',
      'Mitrani',
      'Naranjos',
      'New Jersey',
      'Nuestra Señora de La Paz',
      'Nueva Escocia',
      'Nueva Esperanza',
      'Nueva Granada',
      'Nuevo Chile',
      'Olarte',
      'Osorio X',
      'Osorio XIII',
      'Parcela El Porvenir',
      'Paso Ancho',
      'Piamonte',
      'Porvenir',
      'Potreritos',
      'Potreritos',
      'Primavera Sur',
      'San Antonio',
      'San Antonio de Bosa',
      'San Antonio de Escocia',
      'San Bernardino',
      'San Bernardino II',
      'San Bernardino Sector Potrerito',
      'San Bernardino XIX',
      'San Bernardino XVI',
      'San Bernardino XVII',
      'San Bernardino XVIII',
      'San Bernardino XXII',
      'San Bernardino XXV',
      'San Eugenio',
      'San Javier',
      'San Jorge',
      'San Juanito',
      'San Martín',
      'San Miguel',
      'San Pablo I sector',
      'San Pablo II sector',
      'San Pedro',
      'Santa Fe de Bosa',
      'Santa Fe I',
      'Santa Fe II',
      'Santa Fe III',
      'Santa Inés',
      'Santa Lucía',
      'Sauces',
      'Siracuza',
      'Tokio',
      'Urbanización Acuarela',
      'Vegas de Santana',
      'Vereda San José',
      'Villa Alegre',
      'Villa Alegría',
      'Villa Anny',
      'Villa Bosa',
      'Villa Carolina',
      'Villa Clemencia',
      'Villa Colombia',
      'Villa de Los Comuneros',
      'Villa de Suaita',
      'Villa del Río.',
      'Villa Esmeralda',
      'Villa Karen',
      'Villa Magnolia',
      'Villa Natalia',
      'Villa Nohora',
      'Villa Sonia I',
      'Villa Sonioa II',
      'Villas del Progreso',
      'Villas del Velero',
      'Xochimilco'
    ];
  } else if (localidadElegida == 'Chapinero') {
    return [
      'Antiguo Country',
      'Bellavista',
      'Bosque Calderón',
      'Bosque Calderón Tejada',
      'Bosque Calderón Tejada',
      'Cataluña',
      'Chapinero Alto',
      'Chapinero Central',
      'Chapinero Norte',
      'Chicó Alto',
      'Chicó Norte',
      'Chicó Norte II',
      'Chicó Norte III',
      'Chicó Occidental',
      'Chicó Reservado',
      'El Castillo',
      'El Chicó',
      'El Nogal',
      'El Paraíso',
      'El Refugio',
      'El Retiro',
      'Emaus',
      'Espartillal',
      'Granada',
      'Ingemar2',
      'Juan XXIII',
      'La Cabrera',
      'La Cabrera',
      'La Esperanza Nororiental',
      'La Salle',
      'La Sureña',
      'Lago Gaitán',
      'Las Acacias',
      'Los Olivos',
      'Los Rosales',
      'María Cristina',
      'Mariscal Sucre',
      'Marly',
      'Nueva Granada',
      'Palomar',
      'Pardo Rubio',
      'Porciúncula',
      'Quinta Camacho',
      'San Isidro',
      'San Luis Altos del Cabo.',
      'San Martín de Porres',
      'Seminario',
      'Sucre',
      'Toscana',
      'Villa Anita',
      'Villa del Cerro'
    ];
  } else if (localidadElegida == 'Ciudad Bolívar') {
    return [
      'Álvaro Bernal Segura',
      'Arborizadora Baja',
      'Atlanta',
      'Barranquitos',
      'Bella Flor',
      'Brazuelos de Santo Domingo',
      'Brisas del Volador',
      'Buenavista',
      'Candelaria La Nueva',
      'Capri',
      'Casa linda',
      'Ciudad Milagros',
      'Colmena',
      'Compartir',
      'Domingo Laín',
      'El Bosque',
      'El Castillo',
      'El Mochuelo II',
      'El Paraíso Mirador',
      'El Pedregal',
      'El Satélite',
      'El Triunfo',
      'Esmeralda',
      'Estrella del Sur',
      'Gibraltar',
      'Gibraltar Sur',
      'Hortalizas ',
      'Juan José Rondón',
      'Juan Pablo II',
      'La Alameda',
      'La Cabaña',
      'La Casona',
      'La Coruña',
      'La Escala',
      'La Estrella de Lagos',
      'La Lira',
      'La Playa',
      'La Torre',
      'La Torre',
      'Lagunitas',
      'Las Acacias',
      'las Manas ',
      'Las Manitas',
      'Los Alpes',
      'Los Andes de Nutibara',
      'Lucero Alto',
      'Lucero Bajo',
      'Lucero Medio',
      'Madelena',
      'Marandú',
      'Meissen',
      'México',
      'Millan Los Sauces',
      'Mochuelo Oriental',
      'Naciones Unidas',
      'Nueva Colombia',
      'Paticos',
      'Protecho',
      'Puerta del Llano',
      'Rafael Escamilla',
      'Recuerdo',
      'Rincón del Diamante Villa Gloria',
      'San Fernando Sur',
      'San Francisco',
      'San Luis Sur',
      'Santa Helena',
      'Santa Inés de la Acacia',
      'Santa Rosa Sur',
      'Sauces',
      'Tierra Linda',
      'Villa Helena',
      'Villa Jacky',
      'Vista Hermosa'
    ];
  } else if (localidadElegida == 'Engativá') {
    [
      'Acapulco',
      'Alameda',
      'Álamos',
      'Álamos Norte',
      'Andalucía',
      'Andalucía Parques de Granada',
      'Bellavista Occidental',
      'Bochica',
      'Bochica Compartir',
      'Bolivia',
      'Bosque Popular',
      'Bosques de Granada',
      'Bosques de Mariana',
      'Boyacá',
      'Cataluña',
      'Centauros del Danubio',
      'Ciudad Bachué',
      'Ciudad de Honda',
      'Ciudadela Colsubsidio',
      'Copetroco La Tropical',
      'Cortijo',
      'El Carmelo',
      'El Cedro',
      'El Dorado Industrial',
      'El Dorado - San Joaquín',
      'El Encanto',
      'El Guali',
      'El Laurel',
      'El Lujan',
      'El Mirador',
      'El Muelle',
      'El Palmar',
      'El Paseo',
      'El Portal del Río',
      'El Real',
      'El Refugio',
      'El Salitre',
      'El Triángulo',
      'El Verdún',
      'Engativá - Centro',
      'Estrada',
      'Florencia',
      'Florida Blanca',
      'Garcés Navas',
      'Granada Club Residencial',
      'Granjas El Dorado',
      'La Almería',
      'La Bonanza',
      'La Cabaña',
      'La Española',
      'La Esperanza',
      'La Estradita',
      'La Europa',
      'La Faena',
      'La Granja',
      'La Marcela',
      'La Palestina',
      'La Reliquia',
      'La Riviera',
      'La Rotana',
      'La Salina',
      'La Serena',
      'La Soledad Norte',
      'La Torquigua',
      'Las Ferias',
      'Las Mercedes',
      'Las Palmas',
      'Linterama',
      'Los Álamos',
      'Los Ángeles',
      'Los Cerecitos',
      'Los Cerezos',
      'Los Laureles',
      'Los Laureles - Sabanas El Dorado',
      'Los Monjes',
      'Los Pinos Florencia',
      'Luis Carlos Galán',
      'Luis María Fernández.',
      'Marandú',
      'Maratu',
      'Meissen - Sidauto',
      'Metrópolis',
      'Minuto de Dios',
      'Mirador de los Cerezos',
      'Molinos de Viento',
      'Morisco',
      'Normandía',
      'Normandía Occidental',
      'Palo Blanco',
      'París',
      'París Gaitán',
      'Parques de Granada',
      'Plazuelas del Virrey',
      'Portal de Granada',
      'Porvenir',
      'Primavera Norte',
      'Puerto Amor - Playas del Jaboque',
      'Quirigua',
      'Rincón de Granada',
      'Sabana del Dorado',
      'San Antonio Norte',
      'San Basilio',
      'San Ignacio',
      'San Joaquin',
      'San José Obrero',
      'San Marcos',
      'Santa Cecilia',
      'Santa Helenita',
      'Santa Librada',
      'Santa Lucía Norte',
      'Santa María del Lago',
      'Santa Mónica',
      'Santa Rosita',
      'Santo Domingo',
      'Tabora',
      'Tisquesusa',
      'Veracruz',
      'Villa Amalia',
      'Villa Claver I y II',
      'Villa Constanza',
      'Villa Gladys',
      'Villa Luz',
      'Villa Mary',
      'Villa Sagrario',
      'Villa Sandra',
      'Villa Teresita',
      'Villas de Granada',
      'Villas del Dorado Norte',
      'Villas del Dorado - San Antonio',
      'Villas del Dorado - San Antonio II',
      'Villas del Madrigal',
      'Viña del Mar',
      'Zarzamora'
    ];
  } else if (localidadElegida == 'Fontibón') {
    return [
      'Ambalema',
      'Arabia',
      'Atahualpa',
      'Bahía Solano',
      'Baleares',
      'Belén',
      'Betania',
      'Bohíos',
      'Bosque de Modelia',
      'Boston',
      'Capellania',
      'Carlos Lleras',
      'Centenario',
      'Centro A',
      'Cofradía',
      'El Bogotano',
      'El Carmen',
      'El Cuco',
      'El Franco',
      'El Guadual',
      'El Jardín',
      'El Jordan',
      'El Pedregal',
      'El Portal',
      'El Refugio',
      'El Rincón de Modelia',
      'El Ruby',
      'El Tapete',
      'El Triángulo',
      'Ferrocaja',
      'Flandes',
      'Florencia',
      'Fontibón Centro',
      'Fuentes del Dorado',
      'Granjas de Techo',
      'Hayuelos',
      'HB',
      'Jericó',
      'Kasandra',
      'La Aldea',
      'La Cabaña',
      'La Esperanza',
      'La Esperanza Norte',
      'La Estación',
      'La Felicidad',
      'La Giralda',
      'La Laguna',
      'La Perla',
      'La Rosita',
      'La Zelfita',
      'Las Brisas',
      'Las Flores',
      'Mallorca',
      'Modelia',
      'Modelia Occidental',
      'Montevideo',
      'Moravia',
      'Palestina',
      'Paraíso Bavaria',
      'Prados de la Alameda',
      'Pueblo Nuevo',
      'Puente Grande',
      'Puerta de Teja',
      'Recodo',
      'Rincón Santo',
      'Sabana Grande',
      'Salamanca',
      'Salitre Nor - Occidental',
      'San José',
      'San Pablo',
      'San Pedro - Los Robles',
      'Santa Cecilia',
      'Santander',
      'Santiago Batavia',
      'Sauzalito',
      'Selva Dorada',
      'Tarragona',
      'Torcoroma',
      'Unidad Residencial Montecarlo',
      'Valle Verde',
      'Veracruz',
      'Versalles',
      'Villa Beatriz',
      'Villa Carmenza',
      'Villa Liliana',
      'Villemar',
      'Visión Semiindustrial'
    ];
  } else if (localidadElegida == 'Kennedy') {
    return [
      'Abraham Lincoln',
      'Agrupación Multifamiliar Villa Emilia',
      'Agrupación Pío X',
      'Alameda de Timiza',
      'Alférez Real',
      'Alfonso López Michelsen',
      'Alfonso Montaña',
      'Aloha',
      'Alquería de la Fragua',
      'Alsacia',
      'Altamar',
      'Américas Central',
      'Américas Occidental  II Etapa',
      'Américas Occidental I Etapa',
      'Américas Occidental III Etapa',
      'Antiguo Hipódromo de Techo II Etapa',
      'Áticos de las Américas',
      'Avenida Cundinamarca',
      'Banderas',
      'Barranquillita',
      'Bellavista',
      'Berlín',
      'Boitá I',
      'Boitá II',
      'Bombay',
      'Britalita',
      'Calandaima',
      'Calarcá I',
      'Calarcá II',
      'Campo Hermoso',
      'Carimagua I',
      'Carvajal',
      'Carvajal II Sector',
      'Carvajal Osorio',
      'Carvajal Techo',
      'Casa Loma',
      'Casablanca 32 ',
      'Casablanca 33',
      'Casablanca I',
      'Casablanca II',
      'Casablanca III ',
      'Casablanca IV',
      'Casablanca Sur',
      'Catalina',
      'Catalina II',
      'Cayetano Cañizares',
      'Centroaméricas',
      'Chucua de la Vaca',
      'Ciudad Alsacia',
      'Ciudad de Cali',
      'Ciudad Galán',
      'Ciudad Granada',
      'Ciudad Kennedy',
      'Ciudad Kennedy Central',
      'Ciudad Kennedy Norte',
      'Ciudad Kennedy Occidental',
      'Ciudad Kennedy Oriental',
      'Ciudad Kennedy Sur',
      'Ciudad Tintal',
      'Ciudadela Primavera',
      'Ciudadela Tierra Buena',
      'Class',
      'Condado El Rey',
      'Conjunto Residencial Gerona del Tintal',
      'Conjunto Residencial Prados de castilla I',
      'Conjunto Residencial Prados de castilla II',
      'Conjunto Residencial Prados de castilla III',
      'Cooperativa de Suboficiales',
      'Delicias',
      'Desarrollo Nueva York',
      'Dindalito',
      'El Almenar',
      'El Amparo',
      'El Carmelo',
      'El Comité',
      'El Condado de la Paz',
      'El Descanso',
      'El Jordán',
      'El Llantito',
      'El Olivo',
      'El Palenque',
      'El Paraíso',
      'El Patio',
      'El Pencil',
      'El Porvenir',
      'El Progreso I',
      'El progreso II',
      'El Rincón de Mandalay',
      'El Rosario',
      'El Rubí',
      'El Saucedal',
      'El Saucedal',
      'El Tintal',
      'El Triángulo',
      'El Triunfo',
      'Floralia I',
      'Floralia II',
      'Floresta Sur',
      'Fundadores',
      'Galán',
      'Gerona',
      'Glorieta de las Américas',
      'Gran Britalia',
      'Guadalupe',
      'Hipotecho',
      'Horizonte Occidente',
      'Igualdad I',
      'Igualdad II',
      'Jacqueline',
      'Jazmín Occidental',
      'Juan Pablo I',
      'La Cecilia',
      'La Chucua',
      'La Concordia',
      'La Esperanza',
      'La Esperanza',
      'La Giraldilla',
      'La Llanura',
      'La María',
      'La María',
      'La Rivera',
      'La Unidad',
      'Lago Timiza I Etapa',
      'Lago Timiza II Etapa',
      'Las Acacias',
      'Las Américas',
      'Las Brisas',
      'Las Luces',
      'Las Margaritas',
      'Las Palmeras',
      'Las Torres',
      'Llano Grande',
      'Los Almendros',
      'Los Cristales',
      'Los Pinos de Marsella',
      'Los Sauces',
      'Lucerna',
      'Lusitania',
      'Mandalay',
      'María Paz',
      'Marsella',
      'Marsella III',
      'Milenta',
      'Miraflores Kennedy',
      'Moravia II',
      'Multifamiliar Techo',
      'Nuestra Señora de La Paz',
      'Nueva Marsella I',
      'Nueva Marsella II',
      'Nueva Marsella III',
      'Nueva York',
      'Nuevo Kennedy',
      'Nuevo Timiza',
      'Onasis',
      'Osorio',
      'Osorio XI',
      'Osorio XII',
      'Palmitas',
      'Pastrana',
      'Pastrana',
      'Pastranita',
      'Pastranita II',
      'Patio Bonito I',
      'Patio Bonito II',
      'Patio Bonito III',
      'Perpetuo Socorro',
      'Pinar del Río',
      'Portal Américas',
      'Prados de Kennedy',
      'Provivienda',
      'Provivienda Occidental',
      'Provivienda Oriental',
      'Puente La Vega',
      'Puerto José de Caldas',
      'Roma',
      'Roma II',
      'Sagrado Corazón',
      'Salvador Allende',
      'San Andrés I',
      'San Andrés II',
      'San Carlos',
      'San Dionisio',
      'San José Occidental',
      'San Marino',
      'San Martín de Porres',
      'Santa Catalina',
      'Santa Fe del Tintal',
      'Santa María de Kennedy',
      'Santa Mónica',
      'Santa Paz - Santa Elvira',
      'Santa Rosa de Carvajal',
      'Sumapaz',
      'Talavera de la Reina',
      'Tayrona',
      'Tayrona Comercial',
      'Techo',
      'Tierra Buena',
      'Timiza',
      'Tintala',
      'Tintalito I',
      'Tintalito II',
      'Tocarema',
      'Tocarema',
      'Tonoli',
      'Tundama',
      'Unidad Oviedo',
      'Urbanización Bavaria',
      'Urbanización Unir Uno (Predio Calandaima)',
      'Valencia - La Chucua',
      'Vasconia II',
      'Vegas de Santa Ana',
      'Villa Adriana',
      'Villa Alexandra',
      'Villa Andrea',
      'Villa Andrés',
      'Villa Anita',
      'Villa Claudia',
      'Villa de la Loma',
      'Villa de la Torre',
      'Villa de los Sauces',
      'Villa Emilia',
      'Villa Hermosa',
      'Villa Mendoza',
      'Villa Nelly',
      'Villa Nueva',
      'Villa Rica',
      'Villa Zarzamora',
      'Villas de Kennedy',
      'Vista Hermosa'
    ];
  } else if (localidadElegida == 'La Candelaria') {
    return [
      'Belén',
      'Centro Administrativo',
      'Egipto',
      'La Catedral',
      'La Concordia',
      'Las Aguas',
      'Nueva Santa Fe',
      'Santa Bárbara'
    ];
  } else if (localidadElegida == 'Los Mártires') {
    return [
      'Eduardo Santos',
      'El Progreso',
      'El Vergel',
      'Santa Isabel y Veraguas',
      'El Listón',
      'Estación de la Sabana',
      'La Estanzuela',
      'La Favorita',
      'La Pepita',
      'Paloquemao',
      'Panamericano - La Florida',
      'Ricaurte',
      'Samper Mendoza',
      'San Victorino',
      'Santa Fe',
      'Voto Nacional',
      'el Conjunto Residencial Usatama',
      'Unidad Residencial Colseguros',
      'la Unidad Residencial Sans Façon',
      'Bulevar de Sans Façon'
    ];
  } else if (localidadElegida == 'Puente Aranda') {
    return [
      'Alcalá',
      'Alquería',
      'Autopista Sur',
      'Barcelona',
      'Batallón Caldas',
      'Bisas del Galán',
      'Bochica',
      'Camelia Sur',
      'Carabelas',
      'Centro Industrial',
      'Ciudad Montes',
      'Colón',
      'Cundinamarca',
      'El Arpa y La Lira',
      'El Ejido',
      'El Sol',
      'Galán',
      'Gorgonzola',
      'Industrial Centenario',
      'Jazmín',
      'Jorge Gaitán Cortés',
      'La Asunción',
      'La Camelia',
      'La Coruña',
      'La Florida Occidental',
      'La Guaca',
      'La Pradera',
      'La Trinidad',
      'Los Comuneros',
      'Los Ejidos',
      'Los Sauces',
      'Milenta',
      'Muzú',
      'Ortezal',
      'Ospina Pérez',
      'Pensilvania',
      'Ponderosa',
      'Primavera',
      'Puente Aranda',
      'Remanso',
      'Salazar Gómez',
      'San Eusebio',
      'San Francísco',
      'San Gabriel',
      'San Rafael',
      'San Rafael Industrial',
      'Santa Matilde',
      'Santa Rita',
      'Tejar',
      'Tibaná',
      'Torremolinos',
      'Villa del Rosario',
      'Villa Inés',
      'Villa Sonia'
    ];
  } else if (localidadElegida == 'Rafael Uribe Uribe') {
    return [
      'Arboleda Sur',
      'bochica',
      'Bosque de San Carlos',
      'Bravo Páez',
      'Callejón Santa Bárbara',
      'Centenario',
      'Cerros de Oriente',
      'Chircales',
      'Claret',
      'Colinas',
      'Country Sur',
      'Danubio Sur',
      'Diana Turbay',
      'El Consuelo',
      'El Inglés',
      'El Pesebre',
      'El Portal',
      'El Rosal',
      'El Socorro',
      'El Triángulo',
      'Gavaroba',
      'Granjas de San Pablo',
      'Granjas de Santa Sofía',
      'Guiparma',
      'Gustavo Restrepo',
      'Jorge Cavelier La Resurección',
      'La Esperanza Alta',
      'La Merced del Sur',
      'La Paz',
      'La Picota Occidental',
      'La Picota Oriental',
      'La Playa',
      'Las Brisas',
      'Las Lomas',
      'Luis López de Mesa',
      'Marco Fidel Suárez',
      'Marruecos',
      'Matatigres',
      'Mirador del Sur',
      'Molinos',
      'Murillo Toro',
      'Nueva Pensilvania Sur',
      'Olaya',
      'Oswaldo Gómez',
      'Palermo Sur (con las subdivisiones Central)',
      'Pijaos',
      'Pradera Sur',
      'Puerto Rico',
      'Quiroga',
      'Río de Janeiro',
      'San Agustín',
      'San Jorge',
      'San José Sur',
      'San Luis Sur ',
      'San Marcos ',
      'Santa Fonseca',
      'Santa Lucía',
      'Santiago Pérez',
      'Sarasota',
      'Sosiego Sur',
      'Villa Gladys',
      'Villa Mayor Occidental',
      'Villa Morales'
    ];
  } else if (localidadElegida == 'San Cristobal') {
    return [
      '20 de Julio',
      'Aguas Claras',
      'Altamira',
      'Altamira Chiquita',
      'Altos del Poblado',
      'Altos del Virrey',
      'Altos del Zipa',
      'Altos del Zuque',
      'Amapolas',
      'Amapolas II',
      'Antioquia',
      'Atenas I',
      'Ayacucho',
      'Balcón de La Castaña',
      'Barcelona',
      'Barcelona Sur',
      'Barcelona Sur Oriental',
      'Bella Vista Sector Lucero',
      'Bellavista Parte Alta',
      'Bellavista Parte Baja',
      'Bellavista Sur',
      'Bellavista Sur Oriental',
      'Bello Horizonte',
      'Bello Horizonte III Sector',
      'Bosque de Los Alpes',
      'Buenavista Suroriental',
      'Buenos Aires',
      'Calvo Sur',
      'Camino Viejo San Cristóbal',
      'Canadá - San Luis',
      'Canadá La Guirá',
      'Canadá La Guirá II Sector',
      'Cerros de San Vicente',
      'Chiguaza',
      'Ciudad de Londres',
      'Ciudadela Santa Rosa',
      'Córdoba',
      'Corinto',
      'El Ángulo',
      'El Balcón de La Castaña',
      'El Encanto',
      'El Futuro',
      'El Paraíso',
      'El Paraíso Sur Oriental I Sector',
      'El Pilar',
      'El Pinar (República del Canadá II)',
      'El Quindío',
      'El Ramajal (San Pedro)',
      'El Recodo - República de Canadá',
      'El Rodeo',
      'El Triunfo',
      'Golconda',
      'Gran Colombia (Molinos de Oriente)',
      'Granada Sur',
      'Granada Sur III Sector',
      'Horacio Orjuela',
      'Juan Rey (La Paz)',
      'Juan Rey I',
      'Juan Rey II',
      'La Belleza',
      'La Castaña',
      'La Cecilia',
      'La Colmena',
      'La Gloria',
      'La Gloria Baja',
      'La Gloria MZ 11',
      'La Gloria Occidental',
      'La Gloria Oriental',
      'La Gloria San Miguel',
      'La Gran Colombia',
      'La Grovana',
      'La Herradura',
      'La Joyita',
      'La Joyita Centro (Bello Horizonte)',
      'La María',
      'La Nueva Gloria',
      'La Nueva Gloria II Sector',
      'La Península',
      'La Playa',
      'La Roca',
      'La Roca',
      'La Sagrada Familia',
      'La Serafina',
      'La Sierra',
      'La Victoria',
      'La Victoria II Sector',
      'La Victoria III Sector',
      'La Ye',
      'Las Acacias',
      'Las Brisas',
      'Las Columnas',
      'Las Gaviotas',
      'Las Guacamayas I',
      'Las Guacamayas I',
      'Las Guacamayas III',
      'Las Mercedes',
      'Laureles Sur Oriental II Sector',
      'Los Alpes',
      'Los Alpes Futuro',
      'Los Arrayanes Sector Santa Inés',
      'Los Dos Leones',
      'Los Laureles Sur Oriental I Sector',
      'Los Libertadores',
      'Los Libertadores Bosque Diamante Triángulo',
      'Los Libertadores Sector El Tesoro',
      'Los Libertadores Sector La Colina',
      'Los Libertadores Sector San Ignacio',
      'Los Libertadores Sector San Isidro',
      'Los Libertadores Sector San José',
      'Los Libertadores Sector San Luis',
      'Los Libertadores Sector San Miguel',
      'Los Pinares',
      'Los Pinos',
      'Los Puentes',
      'Macarena Los Alpes',
      'Malvinas',
      'Managua',
      'Manantial',
      'Manila',
      'Miraflores',
      'Miraflores',
      'Modelo Sur',
      'Molinos de Oriente',
      'Montebello',
      'Montecarlo',
      'Moralba',
      'Nariño Sur',
      'Nueva Delhi',
      'Nueva España',
      'Nueva España Parte Alta',
      'Nueva Gloria',
      'Nueva Roma',
      'Nuevas Malvinas (El Triunfo)',
      'Panorama',
      'Paseito III',
      'Primero de Mayo',
      'Puente Colorado',
      'Quindío I',
      'Quindío II',
      'Quinta Ramos',
      'Ramajal',
      'República de Venezuela',
      'República del Canadá',
      'República del Canadá - El Pinar',
      'Rincón de La Victoria - Bellavista',
      'Sagrada Familia',
      'San Blas',
      'San Blas (parcelas)',
      'San Blas II Sector',
      'San Cristóbal Alto',
      'San Cristóbal Sur',
      'San Cristóbal Viejo',
      'San Isidro I',
      'San Isidro II',
      'San Isidro Sur',
      'San Jacinto',
      'San Javier',
      'San José',
      'San José Oriental',
      'San José Sur Oriental',
      'San Luis',
      'San Manuel',
      'San Martín de Loba I',
      'San Martín de Loba II',
      'San Martín Sur',
      'San Miguel',
      'San Pedro Sur Oriental',
      'San Rafael Sur Oriental',
      'San Rafael Usme',
      'San Vicente',
      'San Vicente Alto',
      'San Vicente Bajo',
      'San Vicente Sur Oriental',
      'Santa Ana',
      'Santa Ana Sur',
      'Santa Inés',
      'Santa Inés Sur',
      'Santa Rita I',
      'Santa Rita II',
      'Santa Rita III',
      'Santa Rita Sur Oriental',
      'Sosiego',
      'Sur América',
      'Terrazas de Oriente',
      'Triángulo',
      'Triángulo Alto',
      'Triángulo Bajo',
      'Valparaíso',
      'Velódromo',
      'Vereda Altos de San Blas',
      'Villa Albania',
      'Villa Angélica',
      'Villa Angélica(Canadá-La Guirá)',
      'Villa Aurora',
      'Villa Begonia',
      'Villa de Los Alpes',
      'Villa de Los Alpes I',
      'Villa del Cerro,',
      'Villa Javier',
      'Villa Nataly',
      'Villabell',
      'Vitelma',
      'Yomasa'
    ];
  } else if (localidadElegida == 'Santa Fe') {
    return [
      'Atanasio Girardot',
      'Bosque Izquierdo',
      'Cartagena',
      'El Balcón',
      'El Consuelo',
      'El Dorado',
      'El Guavio',
      'El Mirador',
      'El Rocío',
      'El Triunfo',
      'Fabrica de Loza',
      'Germania',
      'Gran Colombia',
      'La Alameda',
      'La Capuchina',
      'La Macarena',
      'La Merced',
      'La Paz Centro ',
      'La Peña',
      'La Perseverancia',
      'Las Cruces',
      'Las Nieves',
      'Los Laches',
      'Lourdes',
      'Parque Central Bavaria',
      'Ramírez',
      'Sagrado Corazón',
      'Samper',
      'San Bernardo',
      'San Diego',
      'San Dionisio',
      'San Martín',
      'San Victorino',
      'Santa Inés',
      'Santa Rosa de Lima',
      'Veracruz',
      'Vitelma'
    ];
  } else if (localidadElegida == 'Suba') {
    return [
      'Acacias',
      'Alaska',
      'Alcalá',
      'Alcázar de Suba',
      'Alhambra',
      'Almendros de Suba',
      'Almendros Norte',
      'Alto de la Toma',
      'Andes Norte',
      'Atabanza',
      'Atenas',
      'Atenas',
      'Batán',
      'Berlín',
      'Bernal y Forero',
      'Bilbao',
      'Bosques de San Jorge',
      'Britalia',
      'Britalia San Diego',
      'Cacihia',
      'Calatrava',
      'Calima Norte',
      'Campanela',
      'Campania',
      'Canodromo',
      'Cantagallo',
      'Cantalejo',
      'Cañiza I',
      'Cañiza II',
      'Cañiza III',
      'Carolina II',
      'Carolina III',
      'Casa Blanca I',
      'Casa Blanca II',
      'Casablanca Norte Suba',
      'Catalayud',
      'Ciudad Jardín Norte',
      'Club los Lagartos',
      'Coasmedas',
      'Colina Campestre',
      'Colinas de Suba',
      'Compartir',
      'Conejera',
      'Córdoba',
      'Costa Azul',
      'Covadonga',
      'Del Monte',
      'El Cedro',
      'El Paraíso de los 12 Apóstoles',
      'El Pencil',
      'El Pinar',
      'El Pórtico',
      'El Recreo de los Frailes',
      'El Salitre',
      'El Velero',
      'Escuela de Carabineros',
      'Estoril',
      'Fontanar del río',
      'Gibraltar',
      'Gilmar',
      'Gloria Lara',
      'Granada Norte',
      'Granjas de Namur',
      'Gratamira',
      'Guaymaral',
      'Guicani',
      'Iberia',
      'Ilarco',
      'Java',
      'Julio Florez',
      'La Academia',
      'La Alborada',
      'La Campiña',
      'La Chocita',
      'La Floresta Norte',
      'La Fontana',
      'La Gaitana',
      'La Isabela',
      'La Sultana',
      'Lagos de Córdoba',
      'Las Flores',
      'Las Orquídeas',
      'Las Villas',
      'Libertadores',
      'Lindaraja',
      'Lisboa',
      'Londres',
      'Los Eliseos',
      'Los Lagos',
      'Los Nogales de Tibabuyes',
      'Los Prados de La Sultana',
      'Madeira',
      'Malibú',
      'Manuela Arluz',
      'Mazurén',
      'Miraflores',
      'Miramar',
      'Mirandela',
      'Mónaco',
      'Monarcas',
      'Morato',
      'Navetas',
      'Niza',
      'Niza IX',
      'Niza Norte',
      'Niza Suba',
      'Niza VIII',
      'Nueva Tibabuyes',
      'Nueva Zelandia',
      'Nuevo Corinto',
      'Nuevo Monterrey',
      'Oikos',
      'Pasadena',
      'Pijao de Oro',
      'Pontevedra',
      'Portal de Las Mercedes',
      'Portales del Norte',
      'Potosí',
      'Pradera de Suba',
      'Prado Jardín',
      'Prado Pinzón',
      'Prado Sur',
      'Prado Veraniego',
      'Prado Veraniego Norte',
      'Prado Veraniego Sur',
      'Prados de Santa Bárbara',
      'Prados de Suba',
      'Prados de Suba',
      'Provenza',
      'Puente Largo',
      'Rincón de Boyacá',
      'Rincón de Iberia',
      'Rincón de Santa Inés',
      'Sabana de Tibabuyes',
      'San Carlos de Suba',
      'San Carlos de Tibabuyes',
      'San Cipriano',
      'San Felipe',
      'San Francisco',
      'San José de Bavaria',
      'San José del Prado',
      'San José del Spring',
      'San Nicolás',
      'San Pedro de Tibabuyes',
      'Santa Catalina',
      'Santa Cecilia',
      'Santa Helena',
      'Santa Isabel',
      'Santa Rita',
      'Santa Rosa',
      'Sotileza',
      'Suba Centro',
      'Suba Compartir',
      'Tarragona',
      'Tejares del Norte',
      'Teusacá',
      'Tibabuyes Universal',
      'Tierra Linda',
      'Toscana',
      'Tuna Alta',
      'Tuna Baja',
      'Turingia',
      'Vereda Suba Cerros',
      'Vereda Suba-Rincón',
      'Vereda Tibabuyes',
      'Verona',
      'Victoria Norte',
      'Villa Cindy',
      'Villa de las Flores',
      'Villa del Campo',
      'Villa del Prado',
      'Villa Delia',
      'Villa Esperanza',
      'Villa Gloria',
      'Villa Hermosa',
      'Villa Lucy',
      'Villa Morena',
      'Villa Susana',
      'Villanova',
      'Vista Bella'
    ];
  } else if (localidadElegida == 'Sumapaz') {
    return [
      'Betania',
      'Capitolio',
      'Chorreras',
      'Concepción',
      'El Istmo',
      'El Toldo',
      'La Unión',
      'Laguna Verde',
      'Lagunitas',
      'Las Ánimas',
      'Las Auras',
      'Las Palmas',
      'Las Sopas',
      'Las Vegas',
      'Los Ríos',
      'Nazareth',
      'Nueva Granada',
      'Peñaliza',
      'Raizal',
      'San Antonio',
      'San José',
      'San Juan de Sumapaz',
      'Santa Rosa',
      'Santo Domingo',
      'Tabaco',
      'Taquecitos',
      'Tunal Alto',
      'Tunal Bajo'
    ];
  } else if (localidadElegida == 'Teusaquillo') {
    return [
      'Acevedo Tejada',
      'Alfonso López Norte',
      'Armenia',
      'Banco Central',
      'Belalcázar',
      'Campin Occidental',
      'Centro Nariño',
      'Chapinero Occidental',
      'Ciudad Salitre Nor-Oriental',
      'Ciudad Salitre Su-Oriental',
      'El Campín',
      'El Recuerdo',
      'Galerías',
      'Gran América',
      'La Esmeralda',
      'La Estrella',
      'La Magdalena',
      'La Soledad',
      'Las Américas',
      'Nicolás de Federmán',
      'Ortezal',
      'Pablo VI',
      'Palermo',
      'Parque Metropolitano Simón Bolívar',
      'Quesada',
      'Quinta Paredes',
      'Rafael Núñez',
      'San Luis',
      'Santa teresita',
      'Teusaquillo'
    ];
  } else if (localidadElegida == 'Tunjuelito') {
    return [
      'Abraham Lincoln',
      'Ciudad Tunal',
      'El Carmen',
      'Fátima',
      'Isla del Sol',
      'Laguneta',
      'Nuevo Muzú',
      'Rincón de Muzú',
      'Rincón de Venecia',
      'Samore',
      'San Benito',
      'San Carlos',
      'San Vicente Ferrer',
      'Tejar de Ontario',
      'Tunjuelito',
      'Venecia',
    ];
  } else if (localidadElegida == 'Usaquén') {
    return [
      'Acacias',
      'Ainsuca',
      'Altablanca',
      'Altos de Serrezuela',
      'Antigua',
      'Babilonia',
      'Balcones de Vista Hermosa',
      'Balmoral Norte',
      'Barrancas',
      'Bella Suiza',
      'Bellavista',
      'Belmira',
      'Bosque de Pinos',
      'Bosque de San Antonio',
      'Bosque Medina',
      'Buenavista',
      'California',
      'Campo Alegre',
      'Canaima',
      'Caobos Salazar',
      'Capri',
      'Cedritos',
      'Cedro Bolívar',
      'Cedro Golf',
      'Cedro Madeira',
      'Cedro Narváez',
      'Cedro Salazar',
      'Cerro Norte',
      'Chaparral',
      'Conjunto Camino del Palmar',
      'Country Club',
      'Danubio',
      'Darandelos',
      'Don Bosco',
      'El Codito',
      'El Contador',
      'el Nogal',
      'El Pañuelito',
      'El Pedregal',
      'El Pite',
      'El Redil',
      'El Refugio de San Antonio',
      'El Rincón de Las Margaritas',
      'El Toberín',
      'El Verbenal',
      'Escuela de Caballería I',
      'Escuela de Infantería',
      'Estrella del Norte',
      'Francisco Miranda',
      'Ginebra',
      'Guanoa',
      'Horizontes',
      'Jardín Norte',
      'La Calleja',
      'La Carolina',
      'La Cita',
      'La Cristalina',
      'La Esperanza',
      'La Estrellita',
      'La Floresta de La Sabana ',
      'La Frontera',
      'La Glorieta',
      'La Granja Norte',
      'La Liberia',
      'La Llanurita',
      'La Perla Oriental',
      'La Pradera Norte',
      'La Sonora',
      'La Uribe',
      'Las Areneras',
      'Las Delicias del Carmen',
      'Las Margaritas',
      'Las Orquídeas',
      'Lisboa',
      'Los Cedros',
      'Los Cedros Oriental',
      'Los Consuelos',
      'Los Naranjos',
      'Marantá',
      'Maturín',
      'Medellín',
      'Milán (Barrancas)',
      'Mirador del Norte',
      'Molinos del Norte',
      'Montearroyo',
      'Multicentro',
      'Navarra',
      'Nueva Autopista',
      'Nuevo Country',
      'Nuevo Horizonte',
      'Pantanito',
      'Pradera Norte',
      'Prados del Country',
      'Recodo del Country',
      'Rincón del Chicó',
      'Sagrado Corazón',
      'San Antonio Norte',
      'San Cristóbal Norte',
      'San Cristóbal Norte parte alta',
      'San Cristóbal Norte parte baja',
      'San Gabriel',
      'San Juan Bosco',
      'San Patricio',
      'Santa Ana',
      'Santa Ana Occidental',
      'Santa Bárbara',
      'Santa Bárbara',
      'Santa Bárbara Alta',
      'Santa Bárbara Central',
      'Santa Bárbara Occidental',
      'Santa Bárbara Oriental',
      'Santa Bibiana',
      'Santa Coloma',
      'Santa Mónica',
      'Santa Paula',
      'Santa Teresa',
      'Santandersito',
      'Sierras del Moral',
      'Soatama',
      'Soratama',
      'Tibabita',
      'Toledo',
      'Torca',
      'Torcoroma',
      'Torres del Country',
      'Unicerros',
      'Urbanización Los Laureles',
      'Usaquén',
      'Vergel del Country',
      'Villa Magdala',
      'Villa Nydia',
      'Villa Oliva',
      'Villas de Aranjuez',
      'Villas del Mediterráneo',
      'Viña del Mar',
      'Zaragoza'
    ];
  } else if (localidadElegida == 'Usme') {
    return [
      'Alaska',
      'Alfonso López Sector Buenos Aires',
      'Alfonso López Sector Charalá',
      'Alfonso López Sector El Progreso',
      'Almirante Padilla',
      'Altos del Pino',
      'Antonio José de Sucre I',
      'Antonio José de Sucre II',
      'Antonio José de Sucre III',
      'Arizona',
      'Arrayanes',
      'Arrayanes',
      'Barranquillita',
      'Bellavista Alta',
      'Bellavista II Sector',
      'Benjamin Uribe',
      'Betania',
      'Betania II',
      'Bolonia',
      'Bolonia',
      'Bosque El Limonar',
      'Bosque El Limonar II Sector',
      'Brazuelos',
      'Brazuelos - El Paraíso',
      'Brazuelos - La Esmeralda',
      'Brazuelos Occidental',
      'Brisas del Llano',
      'Brisas del Llano',
      'Buenos Aires',
      'Bulevar del Sur',
      'Casa Loma II',
      'Casa Rey',
      'Casaloma',
      'Centro Educativo San José',
      'Chapinerito',
      'Chicó Sur',
      'Chicó Sur II',
      'Ciudadela Cantarrana I',
      'Ciudadela Cantarrana II',
      'Ciudadela Cantarrana III',
      'Ciudadela El Oasis',
      'Compostela I',
      'Compostela II',
      'Compostela III',
      'Comuneros',
      'Costa Rica',
      'Danubio Azul',
      'Daza Sector II',
      'Doña Liliana',
      'Duitama',
      'El Bosque',
      'El Bosque Central',
      'El Bosque km. 11',
      'El Bosque km. 11',
      'El Brillante',
      'El Cortijo',
      'El Curubo',
      'El Espino',
      'El Jordán',
      'El Mortiño',
      'El Nevado',
      'El Nuevo Portal',
      'El Nuevo Portal II',
      'El Paraíso',
      'El Pedregal',
      'El Pedregal - La Lira',
      'El Portal II Etapa',
      'El Porvenir',
      'El Porvenir II Sector',
      'El Progreso Usme',
      'El Recuerdo Sur',
      'El Refugio',
      'El Refugio I',
      'El Refugio I y II',
      'El Refugio Sector Santa Librada',
      'El Rosal-Mirador',
      'El Rubí',
      'El Rubí II Sector',
      'El Salteador',
      'El Triángulo',
      'El Tuno',
      'El Uval',
      'El Uval II Sector',
      'El Virrey Última Etapa',
      'Finca La Esperanza',
      'Fiscala II La Fortuna',
      'Fiscala Sector Centro',
      'Gran Yomasa I',
      'Gran Yomasa II',
      'Juan José Rondón',
      'Juan José Rondón II Sector',
      'La Andrea',
      'La Aurora',
      'La Cabaña',
      'La Cabaña',
      'La Esmeralda-El Recuerdo',
      'La Esperanza',
      'La Esperanza',
      'La Esperanza km. 10',
      'La Esperanza Sur',
      'La Fiscala Sector Daza',
      'La Fiscala Sector Norte',
      'La Fiscala Sector Rodríguez',
      'La Fiscala-Los Tres Laureles',
      'La Fiscala-Lote 16',
      'La Fiscala-Lote 16A',
      'La Flora - Parcelación San Pedro',
      'La Fortaleza',
      'La Huerta',
      'La María',
      'La Morena I',
      'La Morena II',
      'La Morena II (Sector Villa Sandra)',
      'La Orquídea Usme',
      'La Reforma',
      'La Regadera km. 11',
      'La Regadera Sur',
      'Las Brisas',
      'Las Flores',
      'Las Granjas de San Pedro (Santa Librada)',
      'Las Mercedes',
      'Las Violetas',
      'Las Viviendas',
      'Lorenzo Alcantuz I',
      'Lorenzo Alcantuz II',
      'Los Altos del Brazuelo',
      'Los Arrayanes',
      'Los Olivares',
      'Los Soches',
      'Los Tejares Sur II Sector',
      'Marichuela III',
      'Monteblanco',
      'Montevídeo',
      'Nueva Esperanza',
      'Nuevo Porvenir',
      'Nuevo Progreso-El Progreso II Sector',
      'Nuevo San Andrés de Los Altos',
      'Nuevo San Luis',
      'Olivares',
      'Pepinitos',
      'Picota Sur',
      'Portal de La Vega',
      'Portal de Oriente',
      'Portal del Divino',
      'Porvenir',
      'Puerta al Llano',
      'Puerta al Llano II',
      'Refugio I',
      'Salazar Salazar',
      'San Andrés Alto',
      'San Felipe',
      'San Isidro Sur',
      'San Joaquín-El Uval',
      'San Juan  III',
      'San Juan Bautista',
      'San Juan I',
      'San Juan II',
      'San Luis',
      'San Martín',
      'San Pablo',
      'Santa Librada',
      'Santa Librada Norte',
      'Santa Librada Sector La Peña,'
          'Santa Librada-La Esperanza',
      'Santa Librada-La Sureña',
      'Santa Librada-Los Tejares (Gran Yomasa)',
      'Santa Librada-Salazar Salazar',
      'Santa Librada-San Bernardino',
      'Santa Librada-San Francisco',
      'Santa Marta II',
      'Santa Martha',
      'Sector Granjas de San Pedro',
      'Sierra Morena',
      'Tenerife',
      'Tenerife II Sector',
      'Tihuaque',
      'Tocaimita Oriental',
      'Tocaimita Sur',
      'Unión',
      'Urbanización Brasilia II Sector',
      'Urbanización Brasilia Sur',
      'Urbanización Cartagena',
      'Urbanización Chuniza I',
      'Urbanización Costa Rica - San Andrés de los Altos',
      'Urbanización Jarón Monte Rubio',
      'Urbanización La Andrea',
      'Urbanización La Aurora II',
      'Urbanización Líbano',
      'Urbanización Marichuela',
      'Urbanización Miravalle',
      'Urbanización Tequendama',
      'Usme - Centro',
      'Usminia',
      'Valles de Cafam',
      'Vianey',
      'Villa Alejandría',
      'Villa Alemania',
      'Villa Alemania II Sector',
      'Villa Anita Sur',
      'Villa Diana',
      'Villa Hermosa',
      'Villa Israel',
      'Villa Israel II',
      'Villa Neiza',
      'Villa Nelly',
      'Villa Rosita',
      'Villas de Santa Isabel (Parque Entrenubes)',
      'Villas del Edén',
      'Yomasit'
    ];
  }
  return ['Vacio'];
}

bool showSearchResult(
  String textSearchFor,
  String textSearchin,
) {
  return textSearchin.contains(textSearchFor);
}
